//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerPropspectPro.ObjectModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddrId { get; set; }
        public string AddrLine1 { get; set; }
        public string AddrLine2 { get; set; }
        public string AddrZip { get; set; }
        public string AddrZip4 { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
    
        public virtual Contact Contact { get; set; }
        public virtual Prospect Prospect { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
