//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerPropspectPro.ObjectModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Touch
    {
        public int TouchId { get; set; }
        public string TouchDate { get; set; }
        public string TouchType { get; set; }
        public string TouchNotes { get; set; }
    
        public virtual Prospect Prospect { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
